version: '3.8'

services:

  redis:
    image: redis:7.0.11-alpine
    container_name: redis
    ports:
      - 6379:6379

  django:
    container_name: django
    build: 
      context: .
      no_cache: true
    command: gunicorn my_notepad.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - static_files:/usr/src/app/static
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db

  nginx:
    build: 
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      - static_files:/home/notepad/staticfiles
    depends_on:
      - django

  celery:
    container_name: celery
    build: 
      context: .
      no_cache: true
    command: celery --app=my_notepad worker -l INFO
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env
    depends_on: 
      - django
      - redis
      - db

  db:
    image: postgres:15.4
    container_name: db
    ports:
      - 5435:5432
    env_file:
      - ./.env
    volumes:
      - /Users/ilyapetrov/notepad_db:/var/lib/postgresql/data  

volumes:
  static_files:
    