version: '3.8'

services:

  django:
    container_name: django
    build: 
      context: .
      no_cache: true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env
    ports:
      - 8001:8000
    depends_on:
      - db

  db:
    image: postgres:15.4
    container_name: db
    ports:
      - 5435:5432
    env_file:
      - ./.env
    volumes:
      - /Users/ilyapetrov/notepad_db:/var/lib/postgresql/data  

    