# Generated by Django 3.2.18 on 2023-03-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_note_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
        migrations.AddField(
            model_name='note',
            name='create',
            field=models.DateTimeField(default='2023-03-19 19:05'),
        ),
        migrations.AddField(
            model_name='note',
            name='update',
            field=models.DateTimeField(default='2023-03-19 19:05'),
        ),
    ]
