# Generated by Django 3.2.18 on 2023-03-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20230319_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='create',
            field=models.DateTimeField(default='2023-03-19'),
        ),
        migrations.AlterField(
            model_name='note',
            name='update',
            field=models.DateTimeField(default='2023-03-19'),
        ),
    ]
