# Generated by Django 3.2.18 on 2023-03-19 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_auto_20230319_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 19, 19, 55, 880794)),
        ),
        migrations.AlterField(
            model_name='note',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 19, 19, 19, 55, 880810)),
        ),
    ]
