# Generated by Django 3.2.18 on 2023-03-20 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_auto_20230319_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 14, 6, 27, 731096, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='note',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 14, 6, 27, 731117, tzinfo=utc)),
        ),
    ]
