# Generated by Django 3.2.18 on 2023-03-28 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_auto_20230320_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 12, 35, 32, 634611, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='note',
            name='update',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 28, 12, 35, 32, 634631, tzinfo=utc)),
        ),
    ]
