# Generated by Django 3.2.18 on 2023-04-21 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_auto_20230421_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.AddField(
            model_name='note',
            name='username',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 21, 13, 23, 18, 464549, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 21, 13, 23, 18, 464567, tzinfo=utc), null=True),
        ),
    ]
