# Generated by Django 4.2.7 on 2024-01-03 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0011_auto_20230421_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 3, 19, 8, 26, 913291, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 3, 19, 8, 26, 913434, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
