# Generated by Django 4.2.7 on 2024-01-18 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0014_note_slug_alter_note_create_alter_note_update_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='username',
            new_name='username_id',
        ),
        migrations.AlterField(
            model_name='note',
            name='create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 18, 16, 29, 37, 696511, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 18, 16, 29, 37, 696681, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
