# Generated by Django 4.2.7 on 2024-03-11 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0025_alter_note_content_alter_note_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 11, 18, 45, 57, 168078), null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 11, 18, 45, 57, 168089), null=True),
        ),
    ]
